"""empty message

Revision ID: 696d51e5611f
Revises: 
Create Date: 2021-02-04 11:10:31.561523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696d51e5611f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_antagonist_sets', table_name='antagonist')
    op.drop_column('antagonist', 'sets')
    op.add_column('user', sa.Column('registered_at', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_registered_at'), 'user', ['registered_at'], unique=False)
    op.drop_index('ix_workout_sets', table_name='workout')
    op.drop_column('workout', 'sets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_workout_sets', 'workout', ['sets'], unique=False)
    op.drop_index(op.f('ix_user_registered_at'), table_name='user')
    op.drop_column('user', 'registered_at')
    op.add_column('antagonist', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_antagonist_sets', 'antagonist', ['sets'], unique=False)
    # ### end Alembic commands ###
